import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout"; // Import the client-side layout
import { AppProvider } from "../context/AppContext";
import NavBar from "@/components/ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Virtual Mall Lahore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClientLayout>{children}</ClientLayout>
          {/* <NavBar />*/}
        </body>
      </html>
    </AppProvider>
  );
}
