import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "../components/HeaderTop";
// Import HeaderTop once
import HeaderMain from "../components/headermain";
import NavBar from "../components/navbar";
import NewProducts from "../components/NewProducts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Virtual Mall Lahore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Top Header */}
        <HeaderTop />

        {/* Main Header */}
        <HeaderMain />

        {/* Navigation Bar */}
        <NavBar />

        {/* Main Page Content */}

        {children}
      </body>
    </html>
  );
}
