import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout"; // Import the client-side layout

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Virtual Mall Lahore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
